### PR TITLE
Promote drafter-npm usage over Protagonist

### PR DESCRIPTION
**Pull request by kylef**
Users should prefer to use the [Drafter NPM](https://github.com/apiaryio/drafter-npm) package directly. Drafter NPM will automatically attempt to install Protagonist, the faster native C++ parser and fallback to drafter.js, a native JS parser.

### CODE REVIEW

**Comment by w-vi** [comment]
I think that we should give a reason why the users should prefer drafter-npm package over protagonist.

**Comment by kylef** [comment]
> I think that we should give a reason why the users should prefer drafter-npm package over protagonist.

I was trying to not repeat myself multiple times. I think this would be clear as soon as the user takes a look at Drafter NPM since it's mentioned there.

Do you think it's a good idea to put it here too?

**Comment by w-vi** [comment]
I would put it here but simplified ... something like:

```
*NOTE:** *For general use we recommend that you use the [Drafter NPM](https://github.com/apiaryio/drafter-npm) package instead of Protagonist directly as Protagonist needs to be compiled which may not be possible in every situation*
```

**Comment by kylef** [comment]
Amended to use your message, much better.

**Pull request merged**
