### PR TITLE
Strip out all unnecessary files from NPM package

### PR DESCRIPTION
**Pull request by kylef**
We're including files that don't need to go to the release tarball which is increasing the size.

So I feel confortable removing files from the tarball, I've added a smoke test which tests that we can install (and build) Protagonist from the packaged tarball.

##### Before

```
npm notice filename:      protagonist-2.0.0-pre.5.tgz             
npm notice package size:  2.3 MB                                  
npm notice unpacked size: 15.2 MB  
```

##### After

```
npm notice filename:      protagonist-2.0.0-pre.5.tgz             
npm notice package size:  1.3 MB                                  
npm notice unpacked size: 10.2 MB     
```

### CODE REVIEW

**Comment by kylef** [comment]
@honzajavorek We'd have to list an awful lot of files, I am not sure it is feasible to maintain a list of all the files (take a look at the result of `npm pack` in https://circleci.com/gh/apiaryio/protagonist/698?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by honzajavorek** [comment]
@kylef `files` supports glob patterns the same way `.npmignore` does. What is the difference then in where the awful list is? I still think it makes more sense to specify what should go in than what shouldn't, especially given I believe the former almost never changes and the later changes all the time (CI configs, lint configs, random output files, etc.)

**Comment by kylef** [comment]
@honzajavorek OK, did not realise I could use globs in files. I'll try this.

**Comment by kylef** [comment]
This is the final size after recent changes:

```
npm notice filename:      protagonist-2.0.0-pre.5.tgz
npm notice package size:  1.3 MB
npm notice unpacked size: 10.2 MB
```

A good amount of that size is from boost, there are a lot of files there but it's unclear what we can cut out as there are many includes against otherfiles and not so simple to analyse the entire tree. I accidentally didn't include it and as I had boost installed globally the package worked.

**Pull request merged**
