### PR TITLE
Update to drafter 2.2.0

### PR DESCRIPTION
**Pull request by kylef**
https://github.com/apiaryio/drafter/releases/tag/v2.2.0

### CODE REVIEW

**Comment by pksunkara** [comment]
Oh, I am not sure about this. There was quite a bit of change in the C++ API of drafter.

**Comment by w-vi** [comment]
@pksunkara what do you mean?

**Comment by pksunkara** [comment]
@w-vi This PR in particular. https://github.com/apiaryio/drafter/pull/212

I am not sure if we actually need to change anything regarding the C++ API, but I need to take a close look at it.

**Comment by pksunkara** [comment]
@kylef Okay, no issues. Everything is compatible.

**Pull request merged**
