### PR TITLE
WrapResult in the thread not on event loop

### PR DESCRIPTION
**Pull request by w-vi**
Once we cleanup the Drafter API Protagonist needs an overhaul on how things are done.

### CODE REVIEW

**Comment by pksunkara** [comment]
Is there a reason why there is a duplication of code (Result::WrapResult)? Why can't we just move the `Result::WrapResult` inside the async part?

**Comment by w-vi** [comment]
No because you can't create v8 objects in the thread pool that needs to be done on the main javascript thread.

**Comment by pksunkara** [comment]
`Result::WrapResult` is just a convenience function for us. We don't have to make it return `Local<Object>`. We can return `sos::Object` and thus remove the duplicate code. I have added a commit to this PR. Please review my commit and then merge the PR.

**Comment by w-vi** [comment]
Please squash it, there is no need for two commits.

**Pull request merged**
